language: php

php:
  - 7.1
  - 7.2

branches:
  except:
    - gh-pages

addons:
  hosts:
    - blank

sudo: false

install:
  - composer install

before_script:
  - export PATH=$PATH:vendor/bin
  - mysql -e "create database IF NOT EXISTS delboy1978uk;\n" -uroot
  - mysql -e "USE mysql;\n" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON *.* TO dbuser@'%' IDENTIFIED BY 'dbpass';\n" -uroot
  - mysql -e "FLUSH PRIVILEGES;\n" -uroot
  - migrant migrate --no-interaction
  - migrant generate-proxies

script:
  - php vendor/bin/codecept run unit --coverage-xml --env travis

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml
